
dashboard_xls = [['ERP End Customer Name', '', -1],
                 ['End Customer Global Ultimate Name', '', -1],
                 ['PSS', '', -1],
                 ['TSA', '', -1],
                 ['AS PM', '', -1],
                 ['AS CSE', '', -1],
                 ['AS Status', '', -1],
                 ['SAAS Status', '', -1],
                 ['CX Contact', '', -1],
                 ['CX Status', '', -1],
                 ['Renewal Date(s)', '', -1],
                 ['Total Bookings', '', -1],
                 ['Service Bookings', '', -1],
                 ['Product Type', '', -1],
                 ['Bundle Product ID', '', -1],
                 ['Product Description', '', -1],
                 ['Sensor Count', '', -1],
                 ['Active Sensors', '', -1],
                 ['Sales Level 1', '', -1],
                 ['Sales Level 2', '', -1],
                 ['Sales Level 3', '', -1],
                 ['Sales Level 4', '', -1],
                 ['Sales Level 5', '', -1],
                 ['Sales Level 6', '', -1]]
